pypos/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from pypos.db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'

        if error is None:
            try:
                db.execute(
                    "INSERT INTO user (username, password) VALUES (?, ?)",
                    (username, generate_password_hash(password)),
                )
                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        user = db.execute(
            'SELECT * FROM user WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))

        flash(error)

    return render_template('auth/login.html')


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM user WHERE id = ?', (user_id,)
        ).fetchone()


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

pypos/blueprints/frontend/__init__.py
from flask import Blueprint

bp = Blueprint('page', __name__)
from .views import *

pypos/templates/_partials/footer.html
<div class="container">
    <hr>
    <div class="gb-logo-container mb-3">
        <a href="https://github.com/pedro-psb/pypos-canteen">
            <img src="{{ url_for('static', filename='img/github-light-2.png') }}" alt="github logo">
        </a>
    </div>
    <div>
        PyPos Canteen - Almost All Rights reserved
    </div>
</div>

pypos/templates/_partials/navbar.html
<div class="container pb-3">
    <div class="d-flex flex-column flex-md-row align-items-center">
        <!-- logo -->
        <a href="/" class="d-flex img-container">
            <img src="{{ url_for('static', filename='img/logo-orange.png') }}" alt="PyPos Logo">
        </a>
        <!-- menu -->
        <nav class="d-inline-flex ms-md-auto">
            <a class="p-2 text-decoration-none nav-link active" href="{{ url_for('page.index') }}">Home</a>
            <a class="p-2 text-decoration-none nav-link" href="{{ url_for('page.getting_started') }}">Getting Started</a>
            {% if not g.user %}
            <a class="p-2 text-decoration-none nav-link" href="{{ url_for ('page.register_client') }}">Join Canteen</a>
            <a class="btn btn-primary" href="{{ url_for('page.login') }}">Login</a>
            {% elif 'acess_canteen_index' in session['permissions'] %}
            <a class="p-2 text-decoration-none nav-link" href="{{ url_for('page.pos_main') }}">User Area</a>
            <a class="btn btn-primary" href="{{ url_for('auth.logout') }}">Log Out</a>
            {% else %}
            <a class="p-2 text-decoration-none nav-link" href="{{ url_for('page.client_index') }}">User Area</a>
            <a class="btn btn-primary" href="{{ url_for('auth.logout') }}">Log Out</a>
            {% endif %}
        </nav>
    </div>
</div>